# Generated by Django 4.2.5 on 2023-09-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='discord_id',
            field=models.BigIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username_with_tag',
            field=models.CharField(default=1, max_length=150, verbose_name='Username with tag'),
            preserve_default=False,
        ),
    ]
